#if !canImport(ObjectiveC)
import XCTest

extension MailMessageTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MailMessageTests = [
        ("test_contentTransferEncoding", test_contentTransferEncoding),
        ("test_contentTransferEncodingStream", test_contentTransferEncodingStream),
        ("test_file", test_file),
        ("test_fileAttached", test_fileAttached),
        ("test_fullMessage", test_fullMessage),
        ("test_headerValues", test_headerValues),
        ("test_mimeEncode_contentType", test_mimeEncode_contentType),
        ("test_mimeEncode_parameter", test_mimeEncode_parameter),
        ("test_mimeEncode", test_mimeEncode),
        ("test_parser", test_parser),
        ("test_plainText", test_plainText),
        ("test_richText", test_richText),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(MailMessageTests.__allTests__MailMessageTests),
    ]
}
#endif
